### ISSUE TITLE
problem while attempting to convert a regular Go game played on KGS server to a full GIF 

### ISSUE THREAD

**Issue by Stepansky0012** [travisgk/sgf2anim#3]
Dear travisgk
First of all, I want to express my sincere appreciation for your fantastic work on this project. I truly believe it has the potential to be something truly special. The ability to convert SGF files to GIFs is incredibly useful and the overall quality of your work is evident.
However, I encountered a problem while attempting to convert a regular Go game played on KGS server to a full GIF. The conversion stopped mid-game, and I believe this is due to the illegal move check logic. 
Here's some more information about the game:
* Board size: 19x19
* The game includes capturing groups of stones and Ko fights. 
* The game was played according to the rules.
I'm particularly enthusiastic about the potential for customizing the game board, as I find this feature very valuable. 
I hope this bug can be resolved soon, as it prevents me from fully enjoying your amazing product. Thank you again for your hard work. 
[KaTrain_Koogo vs stepansky 2024-10-20 01 30 35.zip](https://github.com/user-attachments/files/17953896/KaTrain_Koogo.vs.stepansky.2024-10-20.01.30.35.zip)

**Comment by travisgk** [comment]
Hello Stepansky,

I'm really glad to hear you appreciate my project and that you find it promising. I've taken a look at your game file and discovered that it was generated by KGS using KaTrain, which creates a file that's a little more complicated than those I had used when testing my program. 

I've added functionality to recognize these particular files, in which case the program will create a temporary copy of the .sgf file and perform some blunt cleanup on that copy so that it can be processed.

Download the sgf2anim project now and try creating this "demo.py" file that uses sgf2anim to process your game file (located in your home directory):

```
import time
import sgf2anim


def main():
    start_time = time.time()

    sgf_path = "KaTrain_Koogo vs stepansky 2024-10-20 01 30 35.sgf"
    out_path = sgf_path[:-4] + ".gif"

    # sets up the "desert" style and creates a GIF with it.
    sgf2anim.get_settings().set_for_animated_diagram()
    sgf2anim.get_settings().STYLE_NAME = "desert"
    sgf2anim.get_settings().DIGIT_TEXT_SCALE_FACTOR = 0.32
    sgf2anim.get_settings().LEFTWARD_ONE_CLIP_FACTOR = -0.05
    sgf2anim.get_settings().LINE_COLOR = (75, 33, 33)
    sgf2anim.get_settings().LINE_THICKNESS = 1.3
    sgf2anim.get_settings().PLACEMENT_MARKER_COLOR = (30, 5, 5)

    sgf2anim.save_diagram(
        sgf_path=sgf_path,
        out_path=out_path,
        frame_delay_ms=100,
        start_freeze_ms=2000,
        end_freeze_ms=10000,
        number_display_ms=100,
    )

    elapsed = time.time() - start_time
    print(f"that took {elapsed:>.2f} seconds.")


if __name__ == "__main__":
    main()
```

![KaTrain_Koogo vs stepansky 2024-10-20 01 30 35](https://github.com/user-attachments/assets/3624be70-6e3c-4500-bd6b-4fa1a8a85890)

I apologize if any of the project's source code is a bit confusing, my organization in this project isn't as good compared to how I write things now.

I must also add that the project isn't as optimal as it would be if I had written it now. It doesn't make any use of multiprocessing at this moment, so depending on your hardware it could take a minute or so for the GIF to finally be written and saved.

Let me know if you run into any other issues. Have fun!

**Comment by travisgk** [comment]
I must also add that this code isn't as optimal as it would be if I had written it now. It doesn't make any use of multiprocessing, so depending on your hardware it could take a minute or so for the GIF to finally be written and saved.

**Comment by Stepansky0012** [comment]
Oh thank you so much for the quick response! I haven't had a chance to use
such a code yet . I would love to play a game with you and use your code
after the game.

пт, 29 нояб. 2024 г. в 17:38, Travis G_____ ***@***.***>:
